# Generated by Django 4.2.7 on 2026-01-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometrictemplate',
            new_name='biometric_t_admin_i_0d664d_idx',
            old_name='biometric_admin_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='otp_codes_admin_i_d43981_idx',
            old_name='otp_admin_aadhaar_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='otp_codes_admin_i_e0abc1_idx',
            old_name='otp_admin_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='otp_codes_admin_i_26e70f_idx',
            old_name='otp_admin_used_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='voters_admin_i_c8a00f_idx',
            old_name='voters_admin_aadhaar_idx',
        ),
        migrations.RenameIndex(
            model_name='voter',
            new_name='voters_admin_i_f46c5b_idx',
            old_name='voters_admin_voted_idx',
        ),
    ]
