# Generated by Django 4.2.7 on 2026-01-23 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fraud_type', models.CharField(choices=[('duplicate_biometric', 'Duplicate Biometric'), ('multiple_otp_attempts', 'Multiple OTP Attempts'), ('already_voted', 'Already Voted'), ('invalid_session', 'Invalid Session'), ('suspicious_activity', 'Suspicious Activity')], max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('biometric_hash', models.CharField(blank=True, max_length=255)),
                ('booth_number', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to='accounts.admin')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.operator')),
            ],
            options={
                'db_table': 'fraud_logs',
                'indexes': [models.Index(fields=['admin', 'fraud_type', 'flagged_at'], name='fraud_logs_admin_i_74c4b4_idx'), models.Index(fields=['admin', 'reviewed'], name='fraud_logs_admin_i_6f292b_idx'), models.Index(fields=['admin', 'booth_number'], name='fraud_logs_admin_i_0915e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('biometric_scan', 'Biometric Scan'), ('fraud_flagged', 'Fraud Flagged'), ('admin_action', 'Admin Action'), ('operator_created', 'Operator Created')], max_length=100)),
                ('user_type', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('operator', 'Operator')], max_length=20)),
                ('user_id', models.UUIDField()),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.admin')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['admin', 'user_type', 'user_id', 'action'], name='audit_logs_admin_i_3063d8_idx'), models.Index(fields=['admin', 'created_at'], name='audit_logs_admin_i_a8873f_idx')],
            },
        ),
    ]
